package com.redhat.poc.pocdt;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BankUser implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public BankUser() {
    }

}