package com.redhat.poc.pocdt;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label(value = "Gender")
   private java.lang.String gender;
   @org.kie.api.definition.type.Label(value = "Age")
   private int age;
   @org.kie.api.definition.type.Label(value = "Address")
   private java.lang.String address;
   @org.kie.api.definition.type.Label(value = "HasDL")
   private boolean hasDL;
   @org.kie.api.definition.type.Label(value = "SSN")
   private long ssn;
   @org.kie.api.definition.type.Label(value = "Income")
   private double income;
   @org.kie.api.definition.type.Label(value = "MaritalStatus")
   private java.lang.String maritalStatus;

   public Person()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getGender()
   {
      return this.gender;
   }

   public void setGender(java.lang.String gender)
   {
      this.gender = gender;
   }

   public int getAge()
   {
      return this.age;
   }

   public void setAge(int age)
   {
      this.age = age;
   }

   public java.lang.String getAddress()
   {
      return this.address;
   }

   public void setAddress(java.lang.String address)
   {
      this.address = address;
   }

   public boolean isHasDL()
   {
      return this.hasDL;
   }

   public void setHasDL(boolean hasDL)
   {
      this.hasDL = hasDL;
   }

   public long getSsn()
   {
      return this.ssn;
   }

   public void setSsn(long ssn)
   {
      this.ssn = ssn;
   }

   public double getIncome()
   {
      return this.income;
   }

   public void setIncome(double income)
   {
      this.income = income;
   }

   public java.lang.String getMaritalStatus()
   {
      return this.maritalStatus;
   }

   public void setMaritalStatus(java.lang.String maritalStatus)
   {
      this.maritalStatus = maritalStatus;
   }

   public Person(java.lang.String name, java.lang.String gender, int age,
         java.lang.String address, boolean hasDL, long ssn, double income,
         java.lang.String maritalStatus)
   {
      this.name = name;
      this.gender = gender;
      this.age = age;
      this.address = address;
      this.hasDL = hasDL;
      this.ssn = ssn;
      this.income = income;
      this.maritalStatus = maritalStatus;
   }

}